image:
  repository: louislam/uptime-kuma
  tag: "1.23.13-debian" # Version fixe pour l'idempotence

service:
  type: NodePort
  port: 80              # Port interne (DNS)
  targetPort: 3001      # Port du container
  nodePort: 30001       # Port externe (Browser)

persistence:
  enabled: true         # Survie aux red√©marrages
  size: 2Gi