apiVersion: v1
kind: Service
metadata:
  name: {{ include "uptime-kuma.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "uptime-kuma.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations: {{- toYaml .Values.service.annotations | nindent 4 | default "{}" }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 3001
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") (.Values.service.nodePort) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "uptime-kuma.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
